# Site settings
title: Luis Guimaraes
email: luis.csguimaraes@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://luiscsguimaraes.github.io/" # the base hostname & protocol for your site

twitter_username: luiscsguimaraes
github_username: LuisCSGuimaraes

# Build settings
markdown: kramdown
